# us-west-1 is managed by cloudformation

us-west-2:
    default:
        routes:
            # Amazon routes
            AMAZON: IGW

            aus4.mozilla.org: IGW
            aus5.mozilla.org: IGW

            10.132.0.0/16: local
            0.0.0.0/0: VGW

    default-NAT:
            10.48.0.0/15: VGW
            10.50.0.0/15: VGW
            10.132.0.0/16: local
            0.0.0.0/0: NAT

            # Autograph
            autograph-external.prod.autograph.services.mozaws.net: NAT
            autograph-external.stage.autograph.services.mozaws.net: NAT

    upload-nat:
        routes:
            10.132.0.0/16: local
            0.0.0.0/0: IGW


us-east-1:
    default:
        routes:
            10.134.0.0/16: local
            0.0.0.0/0: VGW

    default-NAT:
            10.48.0.0/15: VGW
            10.50.0.0/15: VGW
            10.134.0.0/16: local
            0.0.0.0/0: NAT

            # Autograph
            autograph-external.prod.autograph.services.mozaws.net: NAT
            autograph-external.stage.autograph.services.mozaws.net: NAT

    upload-nat:
        routes:
            10.134.0.0/16: local
            0.0.0.0/0: IGW
