us-west-2:
    vpc-cd63f2a4:
        10.132.48.0/22:
            name: srv
            routing_table: default-NAT

        10.132.30.0/24:
            name: signing
            routing_table: default-NAT

        10.132.31.0/24:
            name: upload-nat
            routing_table: upload-nat


us-east-1:
    vpc-b42100df:
        10.134.48.0/22:
            name: srv
            routing_table: default-NAT

        10.134.68.0/26:
            name: bb
            routing_table: default-NAT

        10.134.30.0/24:
            name: signing
            routing_table: default-NAT

        10.134.31.0/24:
            name: upload-nat
            routing_table: upload-nat
